theme: jekyll-theme-cayman
title: SEC Form 13F Securities data
description: CSV and Excel datasets of SEC Form 13F securities, published quarterly.
show_downloads: false
google_analytics: UA-118405596-1